# Generated by Django 3.1.1 on 2021-05-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0002_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
    ]
