# Generated by Django 3.1.1 on 2021-05-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0005_auto_20210503_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
