# Generated by Django 3.1.1 on 2021-05-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0007_auto_20210517_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='slots',
            field=models.TimeField(blank=True, default=False, null=True),
        ),
    ]
