# Generated by Django 3.1.1 on 2021-05-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0012_auto_20210517_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='appointment',
        ),
        migrations.AddField(
            model_name='patient',
            name='appointment',
            field=models.ManyToManyField(null=True, to='appoint.Appointment'),
        ),
    ]
