# Generated by Django 3.1.1 on 2021-05-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0013_auto_20210517_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slots',
            old_name='frm',
            new_name='time',
        ),
    ]
