# Generated by Django 3.1.1 on 2021-05-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0014_auto_20210517_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='slots',
        ),
        migrations.AddField(
            model_name='doctor',
            name='slots',
            field=models.ManyToManyField(null=True, to='appoint.Slots'),
        ),
    ]
