# Generated by Django 3.1.1 on 2021-05-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0017_auto_20210521_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, default=False, null=True),
        ),
    ]
