# Generated by Django 3.1.1 on 2021-05-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0018_auto_20210521_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(blank=True, default=False, null=True),
        ),
    ]
