# Generated by Django 3.1.1 on 2021-05-21 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0020_auto_20210521_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
