# Generated by Django 3.1.1 on 2021-05-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0021_appointment_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='appointment',
        ),
    ]
