# Generated by Django 3.1.1 on 2021-05-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0022_auto_20210521_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cacelled_by_patient',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by_doctor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='editable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('pending', 'Pending'), ('completed', 'Completed')], default='Pending', max_length=10, null=True),
        ),
    ]
