# Generated by Django 3.1.1 on 2021-05-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0023_auto_20210522_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='cacelled_by_patient',
            new_name='cancelled_by_patient',
        ),
    ]
